### ISSUE TITLE
How about we add a KeyState hook so we can use the main PC to toggle thermal and other things? | Discuss

### ISSUE THREAD

**Issue by MaRf1Mm** [HuiTeab/EFT-DMA-Radar-v2#1]
Hey👋
Great source! It helped me fix my code (I was stuck on displaying value when hovering).
I've been trying to add some way of detecting keystates from the main PC. I figured I could share it here when I'm done.
But I also wanted to give you guys a good idea (as you are superior in coding compared to me).
This "Issue" is more for talking and exchanging code/info/links. Since I didn't find your guys' Discord or some server where you share progress, I figured this is better than not having contact at all.
Here are some links I found helpful when searching for key states:
https://www.unknowncheats.me/forum/c-and-c-/616451-dma-keystate-hook-trouble.html
https://www.unknowncheats.me/forum/c-and-c-/327461-kernel-mode-key-input.html

~~Also, what is No visor? What does it do?~~  I found out

**Comment by xx0m** [comment]
I personally am not bothered nor care to get keystrokes from target pc, however, the other fella working on it may want to, I got no clue

If you end up doing it, just submit a pull request & I'll merge it if its functional & beneficial to the radar but for now it isn't planned

**Comment by HuiTeab** [comment]
Thank you for your kind words and for sharing those resources! It's great to hear that "our" source helped you overcome a hurdle in your project.
Regarding the idea of detecting keystrokes from the main PC, I must say, it’s not something I plan to integrate into our project now or in the foreseeable future.
However, should I ever explore this path, my approach would lean towards utilizing an input manager, specifically tailored to capture keystrokes from the Tarkov application alone. This method promises a more targeted implementation, significantly reducing any concerns related to privacy and security that might arise from broader keystroke detection.
here’s a bit on this approach in a post I came across: [UC LINK](https://www.unknowncheats.me/forum/3298620-post5247.html)
If you’re still intrigued by the potential of this feature, you might find the insights there particularly helpful.

**Comment by MaRf1Mm** [comment]
> Thank you for your kind words and for sharing those resources! It's great to hear that "our" source helped you overcome a hurdle in your project. Regarding the idea of detecting keystrokes from the main PC, I must say, it’s not something I plan to integrate into our project now or in the foreseeable future. However, should I ever explore this path, my approach would lean towards utilizing an input manager, specifically tailored to capture keystrokes from the Tarkov application alone. This method promises a more targeted implementation, significantly reducing any concerns related to privacy and security that might arise from broader keystroke detection. here’s a bit on this approach in a post I came across: [UC LINK](https://www.unknowncheats.me/forum/3298620-post5247.html) If you’re still intrigued by the potential of this feature, you might find the insights there particularly helpful.

> I personally am not bothered nor care to get keystrokes from target pc, however, the other fella working on it may want to, I got no clue
> 
> If you end up doing it, just submit a pull request & I'll merge it if its functional & beneficial to the radar but for now it isn't planned
> 
> [HuiTeab](https://github.com/HuiTeab)'s Discord is available in the ReadMe under Contacts & mine is available on my GitHub profile

Thanks for the source and the UC link; I'm going to look more deeply into that (because, as you were saying, capturing all keystrokes is not good for privacy's sake).
I'm not going to implement it in your code; I just made a basic console output thing if matching keystrokes were detected. 
Then I'm going to send it here (or on Discord), and you guys can polish it and add it into the main (I'm not going to mess with your code structure right now). Also, all your progress in the past three days was like enlightenment for me; I was getting pings that you committed something, then sitting there for like 15 minutes reading all the things you reworked.
![Me every time you post an update](https://github.com/HuiTeab/EFT-DMA-Radar-v2/assets/107577770/086df11b-9b5f-4fbe-8247-0eddeda87166)
