### ISSUE TITLE
ask for misc

### ISSUE THREAD

**Issue by ConnorMAD** [HuiTeab/EFT-DMA-Radar-v2#11]
will you add an option for esp fuser?
and will you add the rest of the maps?
good project, I really appreciate it, it will help a lot of people!
looking forward to new features, soon I'll be able to help with donate

**Comment by xx0m** [comment]
1) not atm, neither of us have a fuser to properly test & develop with & dont think we intend to buy 1 any time soon
2) yeah, masterkeef is working on maps for everyone to use so eventually we will have every map covered, we don't upload all maps atm cus lone has requested we dont

**Comment by alslmany** [comment]
> 1) not atm, neither of us have a fuser to properly test & develop with & dont think we intend to buy 1 any time soon
> 
> 2) yeah, masterkeef is working on maps for everyone to use so eventually we will have every map covered, we don't upload all maps atm cus lone has requested we dont

I'm working on high quality maps, till now I have done Wood, Shorelines, Labs, Factory and customs, (still have some tunings) but if you like I will be more than happy to share it with you.

**Comment by ConnorMAD** [comment]
> > 1. não atm, nenhum de nós tem um fusor para testar e desenvolver e não acho que planejamos comprar 1 tão cedo
> > 2. sim, masterkeef está trabalhando em mapas para todos usarem, então, eventualmente, teremos todos os mapas cobertos, não carregamos todos os mapas, atm cus lone solícito que não
> 
> Estou trabalhando em mapas de alta qualidade, até agora fiz Wood, Shorelines, Labs, Factory e Customs, (ainda tenho algumas configurações) mas se você quiser ficarei mais do que feliz em compartilhar com você.

could you? Do you mind adding me on discord? it's braia100

**Comment by xx0m** [comment]
> > 1. not atm, neither of us have a fuser to properly test & develop with & dont think we intend to buy 1 any time soon
> > 2. yeah, masterkeef is working on maps for everyone to use so eventually we will have every map covered, we don't upload all maps atm cus lone has requested we dont
> 
> I'm working on high quality maps, till now I have done Wood, Shorelines, Labs, Factory and customs, (still have some tunings) but if you like I will be more than happy to share it with you.

Forgot to respond but chuck us some previews

**Comment by matheusbranhan** [comment]
> Forgot to respond but chuck us some previews

He sent it to me, most of the maps are good, but they still need some adjustments, he said it himself.

**Comment by alslmany** [comment]
here is some
![1](https://github.com/HuiTeab/EFT-DMA-Radar-v2/assets/120459419/2fe95b37-9fd9-4764-a5f8-e794c40fd0ef)
![2](https://github.com/HuiTeab/EFT-DMA-Radar-v2/assets/120459419/402dd95d-84f0-4f44-9322-190fb8bd2bad)
![3](https://github.com/HuiTeab/EFT-DMA-Radar-v2/assets/120459419/f2eab88e-dcd5-46b5-b8df-d9c0b9aaf0c9)

**Comment by The30Note** [comment]
@alslmany these are really pretty, have you joined the discord yet? I'm sure they could be implemented, with due credit ofc. Discord link is in read me or add t30n on discord

**Comment by ConnorMAD** [comment]
Add me on discord @HuiTeab or @xx0m , i will send you my maps and you can put in the project?

**Comment by ConnorMAD** [comment]
I'm asking this because my maps are no longer being loaded after updating, there's an error

**Comment by alslmany** [comment]
> I'm asking this because my maps are no longer being loaded after updating, there's an error
> 
> 
> 
> ![image](https://github.com/HuiTeab/EFT-DMA-Radar-v2/assets/120428479/fcfc02db-b361-49dd-8c38-d2301e2e9003)
> 
> 

Just copy the maps folder from the previous build and paste it into the new one
