### ISSUE TITLE
Really important quality improvement 

### ISSUE THREAD

**Issue by Sir9ewwit** [HuiTeab/EFT-DMA-Radar-v2#2]
Hi buddy, I really appreciate the work you've done, seriously. And I'm trying to teach # little by little for the sake of working on the radar. In the meantime, I don't have enough skill. But couple of important things for convenient use i was trying to implement with no success: It would be great if the "Valuable" loot and the loot that we are looking for displayed in the filter would like to be displayed on top of the rest, now it is all blocked by the rest or delete everything else. Also, if several things are located at one point, it would be great to have one point displaying loot on the map and the names scattered on the radar side by side, as a single text in several stacks.

**Comment by xx0m** [comment]
Better loot filter is a work in progress with the ability to create multiple filters that will support diff colours (just gonna hard code colours for starters, eventually will move to gui)
![image](https://github.com/HuiTeab/EFT-DMA-Radar-v2/assets/63579245/33a49f97-4d93-4ff0-b4c5-324e76664689)
![image](https://github.com/HuiTeab/EFT-DMA-Radar-v2/assets/63579245/f72c0bd7-e24b-4611-806c-3ffd2ca553f3)

Added x3 checkboxes in settings to help reduce clutter too
![image](https://github.com/HuiTeab/EFT-DMA-Radar-v2/assets/63579245/186a7069-f219-4e65-9f3c-482aa169da71)

Will get around to displaying containers if multiple items are in same container eventually

I should probably also just rename it from 'important loot' to just 'loot filter'

**Comment by xx0m** [comment]
Pretty sure this is pretty much solved now with the whole loot filter system & 'important / filtered only'. When I have more spare time I'll work on like, displaying containers so that you can hover over them to view items inside of it which should further remove some clutter on top of showing loose loot as usual

**Comment by Sir9ewwit** [comment]
Thank you gentlemen, I completely agree with you, it's much more convenient to work with loot now. Also, your code cleaning turned out to be extremely effective, and the performance on the PC radar has greatly increased.
