### ISSUE TITLE
loaded only customs map

### ISSUE THREAD

**Issue by p4elkaua** [HuiTeab/EFT-DMA-Radar-v2#3]
if adding new maps always load custom, if toggle map (f5) for couple of second load new map and returned custom

**Comment by HuiTeab** [comment]
It appears the issue you're encountering with map loading, particularly when switching between maps, could be related to the "mapID" configurations within your JSON files. The "mapID" is for the system to identify and load the correct map.

Please ensure that your map JSON configurations accurately reflect the following "mapID" values for each corresponding map:

Customs: "bigmap".
Factory: "factory4_day" and "factory4_night".
Ground Zero: "sandbox".
Interchange: "interchange".
Labs: "laboratory".
Reserve: "rezervbase".
Shoreline: "shoreline".
Streets: "tarkovstreets".
Woods: "woods".

Here is an example configuration for reference:
`
{
  "mapID": ["sandbox"],
  "x": 1916,
  "y": 6940,
  "scale": 19,
  "mapLayers": [
    {
      "minHeight": 29,
      "filename": "Maps\\GroundZero3f.jpg"
    },
    {
      "minHeight": 24,
      "filename": "Maps\\GroundZero2f.jpg"
    },
    {
      "minHeight": 17,
      "filename": "Maps\\GroundZero1f.jpg"
    },
    {
      "minHeight": 16,
      "filename": "Maps\\GroundZero-1f.jpg"
    }
  ]
}
`

Ensuring the accuracy of these "mapID" values in your JSON files is imperative for the functioning of map selection and loading.

**Comment by MaRf1Mm** [comment]
Here are all the maps with corresponding JSON files in order. This works for me, but try it for yourself. 
https://dropmefiles.com/kmGeD
