### ISSUE TITLE
Adding Maps

### ISSUE THREAD

**Issue by swzzard** [HuiTeab/EFT-DMA-Radar-v2#5]
Good project. Read the forum and Lone's discussion on how to add maps to the project including JSON files. That said I don't understand where the value for X and Y comes from. He says that it is the Unity Origin Point on the map. Do you know how you find that those coords?

Edit: I have seen other people upload map pngs and .json, just trying to understand the process itself.

**Comment by xx0m** [comment]
You can find those in the Settings tab -> 'Show Map Setup Helper' then go back to Radar tab
