### ISSUE TITLE
How safe is uncommenting the chams write function?

### ISSUE THREAD

**Issue by MaRf1Mm** [HuiTeab/EFT-DMA-Radar-v2#6]
I've been testing some things,
added aimview for important loot ← This is super nice; it helps a lot with finding where loot is hiding more specifically.
I found out there is a chams function that HuiTeab made, but all write functions there are commented out, and I don't think there is code to start chams when the raid loads. So, I've been thinking, how safe is uncommenting it to test? Isn't Tarkov detecting editing something like players' clothing if you do it in an unsafe way?

**Comment by HuiTeab** [comment]
I'm not entirely sure about how safe it is to mess with the chams at the moment. I've only done a bit of testing in offline mode because, from what I understand, making wall chams work might involve creating or finding specific pointers that can be utilized for that purpose.
