### ISSUE TITLE
Configuration issue

### ISSUE THREAD

**Issue by arlohewitt** [HuiTeab/EFT-DMA-Radar-v2#8]
There is an issue with the new features in the configuration.json.

I fixed it on my end by changing 290, 292, 294 in Misc.cs to:
JumpPowerStrength = 1f;        //290
ThrowPowerStrength = 1f;       //292
MagDrillSpeed = 1f;                 //294

If i use a Config.json that is edited to these values ^ it also works fine without changing anything that gets compiled
so im guessing its an issue assembling the .json initially

**Comment by xx0m** [comment]
will be fixed later today with a bunch of other things

**Comment by arlohewitt** [comment]
Good stuff, really appreciate this repo!

I know its not something that is easily answerable but how detectable are the newer features?
I know the Camera features are fine along with recoil stuff 
im just wondering if the skills features are networked to any extent

**Comment by xx0m** [comment]
to our knowledge, modifying skill buffs are safe however modifying the skill level itself isn't, we modify skill buffs so it should in theory be alright but who knows, bsg might randomly 1 day decide to flag & ban anyone changing even buffs

this is why we're on the fence about adding infinite stamina, cus we're not really sure how 'safe' it is, this is just a project for us to learn & have fun with, we aren't extremely experienced with eft/cheese development

using this is 100% at your own risk & we cannot guarantee 100% safety so if you value your account do not use write functionality for maximum safety
