### ISSUE TITLE
Moving Toolbox in misc caused troubles when compiling. Delete toolbox in the Tarkov folder to fix the problem.

### ISSUE THREAD

**Issue by MaRf1Mm** [HuiTeab/EFT-DMA-Radar-v2#9]
x0m is sleeping right now, so the fix is going to be late. If you encounter this issue, just delete Toolbox in the Tarkov folder to fix the problem.

**Comment by MaRf1Mm** [comment]
Woods is crashing radar if quest manager is on.

**Comment by xx0m** [comment]
resolved crashing w/ latest commit
